services:
  frontend:
    build:
      context: ./Frontend/iManager
    ports:
      - "3000:80"

  backend:
    build:
      context: ./Backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/imanagerdb
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - api.security.token.secret="my-secret-token"

  db:
    image: mysql:8
    environment:
      MYSQL_DATABASE: imanagerdb
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
